# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: micasaelei
# "service" is the name of this project. This will also be added to your AWS resource names.
service: bannerService

provider:
  name: aws
  runtime: nodejs22.x
  environment:
    REGION: us-east-1
    BUCKET_NAME: banner-images-ads-daniel-famous-dev

resources:
  Resources:
    BannerImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: banner-images-ads-daniel-famous-dev

functions:
  uploadBanner:
    handler: handlers/uploadBanner.getUploadUrl
    events:
      - httpApi:
          path: /
          method: get