service: bannerService
org: micasadeelei


provider:
  name: aws
  runtime: nodejs22.x
  environment:
    BUCKET: banner-images-ads-daniel-famous-dev
    REGION: us-east-1
    DYNAMODB_TABLE: Banners
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
      Resource: arn:aws:s3:::banner-images-ads-daniel-famous-dev/*

resources:
  Resources: 
    BannerImagesBucket: 
      Type: AWS::S3::Bucket
      Properties:
        BucketName: banner-images-ads-daniel-famous-dev
    BannersTable: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Banners
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: fileName
            AttributeType: S
        KeySchema:
          - AttributeName: fileName
            KeyType: HASH

functions:
  uploadBanner:
    handler: handlers/uploadBanner.getUploadUrl
    events:
      - httpApi:
          path: /upload-banner
          method: post
  confirmUpload:
    handler: handlers/confirmUpload.confirmUpload
    events:
      - httpApi:
          path: /upload-banner
          method: post
